spring:
  application:
    name: book-shop-app
  messages:
    basename: lang.messages

  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    password: testtest4321
    username: testuser
    driver-class-name: org.postgresql.Driver
    data:
      - classpath:data.sql
#    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: 'update'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog.master.xml

server:
  port: 8099