package com.klimov.igor.BookShopApp.DTO;

import com.klimov.igor.BookShopApp.model.author.AuthorEntity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.List;
@ApiModel(description = "data model of book")
public class BookDto {
    @ApiModelProperty(value = "book id generated by db", position = 1)
    private Integer id;
    @ApiModelProperty(value = "mnemonic identifier", position = 2)
    private String slug;
    @ApiModelProperty(value = "book cover image", position = 3)
    private String image;
    @ApiModelProperty(value = "list of authors", position = 4)
    private List<AuthorEntity> authors;
    @ApiModelProperty(value = "title of the book", position = 5)
    private String title;
    @ApiModelProperty(value = "is bestseller?", position = 6)
    private Integer isBestseller;
    @ApiModelProperty(value = "rating of the book", position = 7)
    private Integer rating;
    @ApiModelProperty(value = "status for a given user", position = 8)
    private String status;
    @ApiModelProperty(value = "price", position = 9)
    private Integer price;
    @ApiModelProperty(value = "price with discount")
    private Integer discountPrice;

    public BookDto() {
    }

    public BookDto(Integer id,
                   String slug,
                   String image,
                   List<AuthorEntity> authors,
                   String title,
                   Integer isBestseller,
                   Integer rating,
                   String status,
                   Integer price,
                   Integer discountPrice) {
        this.id = id;
        this.slug = slug;
        this.image = image;
        this.authors = authors;
        this.title = title;
        this.isBestseller = isBestseller;
        this.rating = rating;
        this.status = status;
        this.price = price;
        this.discountPrice = discountPrice;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public List<AuthorEntity> getAuthors() {
        return authors;
    }

    public void setAuthors(List<AuthorEntity> authors) {
        this.authors = authors;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Integer isBestseller() {
        return isBestseller;
    }

    public void setBestseller(Integer bestseller) {
        isBestseller = bestseller;
    }

    public Integer getRating() {
        return rating;
    }

    public void setRating(Integer rating) {
        this.rating = rating;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Integer getPrice() {
        return price;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

    public Integer getDiscountPrice() {
        return discountPrice;
    }

    public void setDiscountPrice(Integer discountPrice) {
        this.discountPrice = discountPrice;
    }
}
